print("Ejercicio 5 - CalificaciónMedia")
print("----------------------------------")
print("Introduce la nota de un alumno: ")
nota1 = float(input())
print("Introduce la nota de un alumno: ")
nota2 = float(input())
print("Introduce la nota de un alumno: ")
nota3 = float(input())
print("Introduce la nota de un alumno: ")
nota4 = float(input())
media = float((nota1+nota2+nota3+nota4)/4)
print("La media de los 4 alumnos es: {0:.2f}" .format(media))